### ISSUE TITLE
agregar más palabras relacionadas

### ISSUE THREAD

**Issue by juanbrujo** [keld0r/hubot-reggaeton#4]
https://github.com/keld0r/hubot-reggaeton/blob/1a02da53f6e657cf5a5fe85ad5d22296541870c1/reggaeton.js#L66

Pasa que no hay mucho conociemiento de cómo se escribe esta mierda de música. te sugiero agregar las que más conozcas como regex:

`(reggaet(o|ó)n|reguet(o|ó)n|regaet(o|ó)n|reget(o|ó)n)` y así

**Comment by keld0r** [comment]
No estaba seguro como hacer esa regex, voy a incluir esa misma,.

**Comment by keld0r** [comment]
Correcciones agregadas
